"""
Django settings for rocketDataAnalyze project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#bn7_s9d2_6$l3f!$1)yxys4cj7x8l#3#wzzov)-+@gm@hj+(&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analyze',  # Tu app de análisis de datos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rocketDataAnalyze.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rocketDataAnalyze.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== CONFIGURACIÓN DE API EXTERNA =====
# API Key para OpenWeatherMap (para Dashboard Ambiental - Requerimiento 1.2)
# Obtén tu API key gratis en: https://openweathermap.org/api
OPENWEATHER_API_KEY = '20e000dd01640ec32d0b0f2a5e40dacf'  # Reemplaza con tu API key real

# Coordenadas por defecto (puedes cambiarlas según tu ubicación)
DEFAULT_LATITUDE = 2.480  # Colombia Popayan(ejemplo)
DEFAULT_LONGITUDE = -76.563


# 2.480, -76.563

# ===== CONFIGURACIÓN DEL COHETE Y FÓRMULAS =====
# Altura base de referencia (metros sobre nivel del mar)
# Esta es la altura donde se encuentra el punto de lanzamiento
ROCKET_BASE_ALTITUDE = 161  # metros - Altura promedio en reposo según datos del sensor en Popayán

# Configuración para cálculo de altura teórica (Fórmula de Littlewood)
LITTLEWOOD_CONFIG = {
    'T0': 288.15,      # K - Temperatura estándar ISA al nivel del mar
    'L': 0.0065,       # K/m - Gradiente térmico atmosférico estándar
    'R': 8.314,        # J/(mol·K) - Constante universal de gases ideales
    'g': 9.80665,      # m/s² - Aceleración gravitacional estándar
    'M': 0.029,        # kg/mol - Masa molar del aire seco
    'USE_LOCAL_TEMP': True,  # Si True, usa temperatura del sensor en lugar de T0 estándar
    'USE_SIMPLIFIED_FORMULA': True,  # Si True, usa fórmula simplificada para alturas pequeñas (más precisa para cohetes de corto alcance)
}

# Porcentaje de datos iniciales considerados como "cohete en reposo"
# Se usa para determinar el punto de lanzamiento
FLIGHT_DETECTION_THRESHOLD = 0.10  # 10% de los datos iniciales

# Altura mínima (en metros) para considerar que el vuelo ha iniciado
# Debe ser mayor a este valor sobre el punto de lanzamiento
MIN_FLIGHT_ALTITUDE = 1.0  # metros